### ISSUE TITLE
Integration yeelight_bt not found when trying to verify its light platform

### ISSUE THREAD

**Issue by asha220** [rytilahti/python-yeelightbt#33]
When I try check config in Home assistant it show this error
"Integration yeelight_bt not found when trying to verify its light platform" 

I tried to place the component in custom_components/light/ and custom_components/yeelight_bt/light
but that doesn't help

Home Assistant version is 0.96.3

**Comment by lasry1** [comment]
I have the same issue, and also had another one that had this issue too but they sorted it out:

https://github.com/jnimmo/hass-dmx/issues/21

I'm trying to do the same with this but i can't make it work

**Comment by rytilahti** [comment]
Thanks for the link @lasry1!

So my understanding is, that the folder inside `custom_components` needs to be called `yeelight_bt` with only two three files in it:
* `__init__.py` (which can be empty)
* light.py which is the code itself, and 
* `manifest.json` like https://developers.home-assistant.io/docs/en/creating_integration_manifest.html

I don't have access to any device to try this myself, so I hope someone else will figure out a solution and create a PR for it.

**Comment by asha220** [comment]
Hi @rytilahti. Yes, problem was in file's structure, I change it and Home Assistant can see this component. Thanks!

**Comment by rytilahti** [comment]
Would you please create a PR on this repository in case someone else comes up looking? That'd be very helpful, thanks!

**Comment by asha220** [comment]
Ок. Some times later. Now I have problem with change color and temp, I want fix it too.

**Comment by lasry1** [comment]
Thanks @rytilahti !
I was able to add it without problems now however i can't get the light working... I don't really know what i'm doing wrong.
I'm using the latest version of HassIO

However if i use the yeelight_bt.py included in this repo (python-yeelightbt/custom_components/light/yeelight_bt.py) the light is always unavailable 

If i use the yeelight_bt.py from python-yeelightbt/custom_components/yeelight_bt/light/yeelight_bt.py then i don't get the light coming up on homeassistant

**Which code should i put into light.py to make it work with hassio?**
